### ISSUE TITLE
ERROR: Cannot uninstall 'imageio' during docker build

### ISSUE THREAD

**Issue by juliussimonelli** [Lydorn/mapalignment#10]
When I run `sh build.sh` I get the following error at [this line](https://github.com/juliussimonelli/mapalignment/blob/dd58936ff78b37651e6ed08180d3ba5db77ccf36/docker/lydorn/anaconda-tensorflow-geo/Dockerfile#L41):
```
ERROR: Cannot uninstall 'imageio'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
The command '/bin/sh -c pip install -U --no-cache-dir scikit-image' returned a non-zero code: 1
```
Do you know if there's a way around this?

**Comment by juliussimonelli** [comment]
It looks like adding
```
RUN rm -rf /opt/conda/lib/python3.6/site-packages/imageio*
```
the line beforehand fixes this.

**Comment by Lydorn** [comment]
Thank you @juliussimonelli , I've updated the Dockerfiles to solve that issue!
