### ISSUE TITLE
sh build.sh desn't build image lydorn/anaconda-tensorflow-geo

### ISSUE THREAD

**Issue by possenalain** [Lydorn/mapalignment#13]
During the dependencies installation "gdal" won't  get installed. Is there a workaround ?

Step 11/20 : RUN pip install gdal==2.2.0 --global-option=build_ext --global-option="-I/usr/include/gdal/"
 ---> Running in 476848dbbfac
Collecting gdal==2.2.0
  Downloading GDAL-2.2.0.tar.gz (473 kB)
/opt/conda/lib/python3.6/site-packages/pip/_internal/commands/install.py:229: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0dzek70a/gdal_f3e176c3050d47e5b8723a49d24853c1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0dzek70a/gdal_f3e176c3050d47e5b8723a49d24853c1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-v7x43aan
         cwd: /tmp/pip-install-0dzek70a/gdal_f3e176c3050d47e5b8723a49d24853c1/
    Complete output (30 lines):
    /opt/conda/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'use_2to3_fixers'
      warnings.warn(msg)
    /opt/conda/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'use_2to3_exclude_fixers'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
        return functools.reduce(getattr, self.attrs, module)
    AttributeError: module 'setuptools.dist' has no attribute 'invalid_unless_false'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0dzek70a/gdal_f3e176c3050d47e5b8723a49d24853c1/setup.py", line 339, in <module>
        **extra )
      File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/conda/lib/python3.6/site-packages/setuptools/dist.py", line 363, in __init__
        _Distribution.__init__(self, attrs)
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/opt/conda/lib/python3.6/site-packages/setuptools/dist.py", line 519, in finalize_options
        ep.load()(self, ep.name, value)
      File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in load
        return self.resolve()
      File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2332, in resolve
        raise ImportError(str(exc))
    ImportError: module 'setuptools.dist' has no attribute 'invalid_unless_false'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/40/f9/8ad67763925b5c4f70a278ed725dc80dc774a4d30daf372a570a2faa9a8d/GDAL-2.2.0.tar.gz#sha256=37dbe574438d05b4ab70a940a1d554ff446334325117492449575edfd2433688 (from https://pypi.org/simple/gdal/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement gdal==2.2.0 (from versions: 1.5.0, 1.5.2, 1.6.0, 1.6.1, 1.7.0, 1.7.1, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.11.0, 1.11.1, 1.11.2, 2.0.0, 2.0.1, 2.1.0, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.4.0, 2.4.2, 2.4.3, 2.4.4, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.2.0, 3.2.1, 3.2.2, 3.2.2.1, 3.2.3, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.5.0, 3.5.0.3, 3.5.1, 3.5.2)
ERROR: No matching distribution found for gdal==2.2.0

**Comment by HarshilSaraiya99** [comment]
Hi @Lydorn 
I am having the same error.

`ERROR: failed to solve: process "/bin/sh -c pip install gdal==2.2.0 --global-option=build_ext --global-option=\"-I/usr/include/gdal/\"" did not complete successfully: exit code: 1` 

Any idea on how to solve this?

**Comment by possenalain** [comment]
I will close the issue as no one tends to resolve it in a long time.
