### ISSUE TITLE
Pre-trained network for AerialImageDataset.

### ISSUE THREAD

**Issue by paganpasta** [Lydorn/mapalignment#2]
The download link seems to be for the **Bradbury Dataset**. Is it possible to share the link for **AerialImageDataset**?

**Comment by Lydorn** [comment]
Sorry for getting back to you so late @MacroMayhem (I didn't know notifications were not sent automatically to me about issues). If I understand correctly you are looking to download the Inria Aerial Image Dataset? You can follow the provided link to the dataset website and register for downloading the dataset here: [https://project.inria.fr/aerialimagelabeling/download/](https://project.inria.fr/aerialimagelabeling/download/).

**Comment by paganpasta** [comment]
> Sorry for getting back to you so late @MacroMayhem (I didn't know notifications were not sent automatically to me about issues). If I understand correctly you are looking to download the Inria Aerial Image Dataset? You can follow the provided link to the dataset website and register for downloading the dataset here: https://project.inria.fr/aerialimagelabeling/download/.

No worries and Thanks :D
