### ISSUE TITLE
Problem of dependencies 

### ISSUE THREAD

**Issue by cthnguyen** [Lydorn/mapalignment#5]
Hello Nicolas, 
I have issues to build the last docker image `anaconda-tensorflow-geo`. I first encounter problems with installing tensorflow gpu from the DockerFile in `anaconda-tensorflow` docker image where the command 
```
RUN pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.10.1-cp36-cp36m-linux_x86_64.whl
```

gives me an error. I solved it by simply replacing it with 

```
RUN pip install --ignore-installed --upgrade tensorflow-gpu
```

But then to build the last image `anaconda-tensorflow-gpu`, I have this error while trying to install opencv3.

> UnsatisfiableError: The following specifications were found to be incompatible with each other:
>   - pip -> python[version='>=3.7,<3.8.0a0']

I checked and python 3.7 is installed on the docker, so I don't understand the issue. 

Could you maybe specify which version of the packages (opencv, tensorflow etc) and of python is needed ?

**Comment by Lydorn** [comment]
Thx for the heads up, I updated the Dockerfiles to force installation of Python 3.6.8 and OpenCV 3.1.0 which should fix the issues. Can you tell me if it works for you now?

**Comment by cthnguyen** [comment]
Thanks ! It almost work, I changed some imports on the Dockerfile in `anaconda-tensorflow-geo`. I changed conda imports for pip as it run a lot faster on my machine for the following packages `opencv`, `pyproj`,  `overpy`, `shapely`, `jsmin`, and there was extra quotation marks for the import of pycocotools from the github. 

```
FROM lydorn/anaconda-tensorflow

MAINTAINER Nicolas Girard <nicolas.jp.girard@gmail.com>

RUN apt-get update && apt-get install -y libgtk2.0

# Image manipulation

RUN pip install opencv-python 

RUN pip install pyproj

## Install gdal
#RUN apt-get update
#RUN apt-get install -y software-properties-common
#RUN apt-add-repository ppa:ubuntugis/ubuntugis-unstable
#RUN apt-get update
#RUN apt-get install -y libgdal-dev
## See https://gist.github.com/cspanring/5680334:
#RUN pip install gdal --global-option=build_ext --global-option="-I/usr/include/gdal/"

# Install gdal
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-add-repository ppa:ubuntugis/ubuntugis-unstable
RUN apt-get update
RUN apt-get install -y libgdal-dev
# See https://gist.github.com/cspanring/5680334:
RUN pip install gdal==2.2.0 --global-option=build_ext --global-option="-I/usr/include/gdal/"

# Install overpy
RUN pip install overpy

# Install shapely
RUN pip install Shapely

# Install pycocotools
#RUN pip install git+https://github.com/crowdai/coco.git#subdirectory=PythonAPI
RUN pip install -U --no-cache-dir scikit-image
RUN pip install -U --no-cache-dir cython
RUN pip install --no-cache-dir git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI

RUN pip install jsmin

#RUN conda install -c anaconda joblib -y

# Cleanup
RUN apt-get clean && \
    apt-get autoremove
```


Then, it run fined and I managed to got some results ! Thanks a lot !

**Comment by Lydorn** [comment]
Great, I'm glad you made it work for you!
