### ISSUE TITLE
AttributeError: module 'math_utils' has no attribute 'to_homogeneous'

### ISSUE THREAD

**Issue by MathisMohand** [Lydorn/mapalignment#6]
Hi,
I've been trying to try and use your code to infer some displacements. However, I've been confronted to this issue (title) and seeing the code in detail, the geo_utils.py calls this function but it doesn't exists.

Is it because last time the geo_utils.py file was modified was (to this date) 19 hours ago while the other files like math_utils were modified 9 months ago ?

**Comment by Lydorn** [comment]
Hi,
Thank you for letting me know, yes indeed I mistakenly did not update the other utils. I pushed a commit to update them just now. Does it work for you now?

**Comment by MathisMohand** [comment]
It is working for math_utils (it has been updated). However I now have a new error : 
`root@c997235f530f /w/p/m/mapalign_multires# python main.py 
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    import test
  File "/workspace/projects/mapalign/mapalign_multires/test.py", line 7, in <module>
    import visualization
  File "../utils/visualization.py", line 9, in <module>
    import polygon_utils
  File "/workspace/projects/mapalign/utils/../../utils/polygon_utils.py", line 15, in <module>
    import smallestenclosingcircle
ModuleNotFoundError: No module named 'smallestenclosingcircle'
`
I don't really know where it comes from, I haven't looked all new files yet.

**Comment by Lydorn** [comment]
Actually smallestenclosingcircle is not used in the code so I removed from polygon_utils.py.
The new commit should remove that error.

**Comment by MathisMohand** [comment]
It is working now thanks. However I had to modify few lines to make it work : 

- In model.py there is `import polygonization_utils` which has to be changed to polygon_utils

- On the quickstart I had to download with the zipfile to get the pretrained models as the `download_pretrained.py` script just created an empty folder ds_fac_8_... in runs.igarss2019 folder
- Had to add `allow_pickle=True` parameter in the np.load function call in file main.py line 111.

**Comment by Lydorn** [comment]
Good you managed to make it work!
And thank you for telling me the changes you had to made, I just
committed them.
I also couldn't make the download script work just now... don't know what's
wring with it!

Best,

Nicolas
