### ISSUE TITLE
tfrecord files on training

### ISSUE THREAD

**Issue by MathisMohand** [Lydorn/mapalignment#7]
Hi,

I wanted to try and train the model, however I encountered some issues, and I can't seem to make it work at the moment.

First, in [dataset_multires.py](https://github.com/Lydorn/mapalignment/blob/master/projects/mapalign/dataset_utils/dataset_multires.py) line 56, there is `.format(dataset, downsampling_factor` while the `1_train.py` script loads the json file in which a float is required as first parameter for this format. I think it is the downsampling factor as it follows ds_fac so I removed the `dataset` parameter in the string format.

Secondly, when the function `get_all_shards` in the same file is called, it returns nothing as files are not existing, I think it was maybe an omission or is there an other way around to make it work ?

**Comment by Lydorn** [comment]
Hi and thank you for letting me know. I updated `dataset_multires.py` to solve the problem, indeed the filename format was not correct. It also solves the problem on the function `get_all_shards` as it will now fetch the correct filepaths.
Let me know if this works for you and if you have any other problem!

**Comment by MathisMohand** [comment]
Thanks for the update, it solved the first problem, however I still don't find the files in get_all_shards, I have this `FileNotFoundError` : 
```
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/data/AerialImageDataset/tfrecords.mapalign.multires.aligned_noisy_1/train'
```
Am I forgetting something to do ? As I don't remember having to create this file / directory and it wasn't included in the dataset

EDIT : Actually didn't use the `preprocess` script on the dataset, should probably work after doing it, will keep you informed

**Comment by Lydorn** [comment]
Ah yes you need to use the `preprocess` script to generate the tfrecords first. Note that they take quite some space on the disk.

**Comment by MathisMohand** [comment]
I don't know if I should put this in this issue, but I am having troubles making the `preprocess_aerial_image_multires.py` work, I encounter this error when launching it : 
```
Processing city bloomington, number 2
downsampling_factor: 1
downsampling_factor: 2
Traceback (most recent call last):
  File "preprocess_aerial_image_multires.py", line 354, in <module>
    main()
  File "preprocess_aerial_image_multires.py", line 332, in main
    config.DISP_MAX_ABS_VALUE)
  File "preprocess_aerial_image_multires.py", line 296, in process_dataset
    writers)
  File "preprocess_aerial_image_multires.py", line 229, in process_image
    save_patch_to_tfrecord(patch, downsampling_factor_writers[downsampling_factor])
  File "preprocess_aerial_image_multires.py", line 127, in save_patch_to_tfrecord
    image_raw = image_utils.convert_array_to_jpg_bytes(patch["image"], mode="RGB")
  File "../../utils/image_utils.py", line 81, in convert_array_to_jpg_bytes
    img = Image.fromarray(image_array, mode=mode)
  File "/opt/conda/lib/python3.6/site-packages/PIL/Image.py", line 2666, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "/opt/conda/lib/python3.6/site-packages/PIL/Image.py", line 2609, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
  File "/opt/conda/lib/python3.6/site-packages/PIL/Image.py", line 2542, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/opt/conda/lib/python3.6/site-packages/PIL/Image.py", line 829, in frombytes
    raise ValueError("not enough image data")
ValueError: not enough image data
```
I have downloaded the dataset and fetched polygons from OSM, so I don't know if the problem comes from me.

**Comment by MathisMohand** [comment]
Looks like I found a way around to make it work, maybe it was updates on some libraries that got me errors. I changed the following lines : 

In `preprocess_aerial_image_multires.py`, in the function `downsample_gt_data` : 
```
downsampled_image = skimage.transform.rescale(image, (1 / downsampling_factor, 1 / downsampling_factor, 1), order=3, preserve_range=True)
```
Instead of previously : 
```
downsampled_image = skimage.transform.rescale(image, 1 / downsampling_factor, order=3, preserve_range=True)
```
This made the rescale function only rescale rows and cols but not the image channels (3) which then rasied an error when trying to open RGB image with only 2 channels for example.
I then did the same for the line with `downsampled_normed_disp_field_maps[i]` : 
It became : 
```
downsampled_normed_disp_field_maps[i] = skimage.transform.rescale(normed_disp_field_maps[i], (1 / downsampling_factor, 1 / downsampling_factor, 1), order=3, preserve_range=True)
```

**Comment by Lydorn** [comment]
I'm glad you made it work, and thanks for telling me which changes you had to make.

**Comment by Lydorn** [comment]
I updated the relevant scripts by adding the argument `multichannel=True` and keeping the scalar argument `scale`.
