### ISSUE TITLE
Not using segmentation image

### ISSUE THREAD

**Issue by MathisMohand** [Lydorn/mapalignment#9]
Hi,

I was going through your code concerning the double U-Net architecture, and in your article you mention the segmentation part being really useful to help discover new buildings or willingly removed ones. However, when reading the code on the inference, I don't see any use of the segmentation image, it's just returned through functions but seems never used.

Am I missing something as I think it should be compared with the new polygons coordinates to get information on buildings and potential missed ones.

Sincerely

**Comment by Lydorn** [comment]
Hi,

You are right the inference code just returns the segmentation. I didn't implement the code to remove or add buildings in polygon format. For adding you can use the polygonization tool of QGIS for example of any other contour finding methods. For deletion you can compute the intersection of map polygons with the segmentation and decide to remove polygons with a low intersection area.

Best,

**Comment by MathisMohand** [comment]
Ok, thank you for your answer, I'll see what I can do with these tools.
